os: windows

matrix:
  include:
  
    - name: "Python 3.7.6"
      language: shell
      before_install:
        - choco install python --version 3.7.7
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade setuptools wheel
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install: pip3 install -r requirements.txt -r requirements-test.txt
      script: pytest
  
    - name: "Python 3.8"
      language: shell
      before_install:
        - choco install python --version 3.8.2
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade setuptools wheel
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install: pip3 install -r requirements.txt -r requirements-test.txt
      script: pytest

  allow_failures:
      - name: "Python 3.8"
