trigger:
- master
- develop


jobs:
- job: setup_env
  displayName: 'Setup Environment'
  strategy:
    matrix:
      Server2019:
        AGENT_NAME: 'AZ-SERVER2019'
      Server2016:
        AGENT_NAME: 'AZ-SERVER2016'
      Windows10:
        AGENT_NAME: 'AZ-WIN10'
      Server2012R2:
        AGENT_NAME: 'AZ-WIN2012R2'
      Windows81:
        AGENT_NAME: 'AZ-WIN81'
      Windows2008R2:
        AGENT_NAME: 'AZ-WIN2008R2'
      Windows7SP1:
        AGENT_NAME: 'AZ-WIN7'
  
  pool:
    name: windows-vms
    demands:
      - agent.name -equals $(AGENT_NAME)
  
  steps:
  - script: |
      python -m pip install --upgrade pip
      pip install --upgrade setuptools wheel
      pip install -r requirements.txt -r requirements-test.txt
    displayName: 'Install dependencies'

  - script: |
      pip install -U pytest pytest-azurepipelines
      pytest -v
    displayName: 'Run Tests'